export const initialFormData = {
  fullName: "",
  dateOfBirth: "",
  age: "",
  phoneNumber: "",
  email: "",
  location: "",
  instagram: "",
  tiktok: "",
  twitter: "",
  onlyfans: "",
  otherLinks: "",
  hoursPerWeek: "",
  adultContentExperience: "",
  cameraSetup: "",
  liveShows: "",
  specialSkills: "",
  partnershipPercentage: "",
  motivation: "",
  additionalInfo: "",
  honeypot: "",
}

export const requiredFields = [
  "fullName",
  "dateOfBirth",
  "age",
  "email",
  "location",
  "instagram",
  "tiktok",
  "hoursPerWeek",
  "adultContentExperience",
  "cameraSetup",
  "liveShows",
  "partnershipPercentage",
  "motivation",
]
